---
driver:
  name: terraform
  root_module_directory: tf_module

provisioner:
  name: terraform

platforms:
  - name: local

verifier:
  name: terraform
  systems:
    - name: tf_inspec
      backend: local

suites:
  - name: tf_inspec